name: New Feature or Improvement
description: Use this form to request features, improvements, or to report tech debt, chores, and spikes.
title: Concise title of the issue
labels: [triage]

body:
  - type: dropdown
    id: issue_type
    attributes:
      label: Type of Issue
      description: Select the type of request.
      options:
        - Feature Request
        - Tech Debt
        - Developer Experience Improvement
        - Chore
        - Spike

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the feature, tech debt, or task.
      placeholder: Describe the issue, feature, or task in detail here.

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Provide additional context, user stories, or any other details that can help understand the request.
      placeholder: Add any additional details or context here.

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Provide clear acceptance criteria or success conditions for this request.
      placeholder: 1. Criteria 1, 2. Criteria 2